import axios from "axios";
import { useState, useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import "./Interview.css";
import toast from "react-hot-toast";

function Interview() {

  const location = useLocation();
  const navigate = useNavigate();
  
  const questions = location.state?.questions || [];
  const interviewType = location.state?.interviewType || "Role";
  const role = location.state?.role || "";

  const [currentQuestion, setCurrentQuestion] = useState(0);

  const [answers, setAnswers] = useState({});

  const handleAnswerChange = (e) => {
    setAnswers({
      ...answers,
      [currentQuestion]: e.target.value,
    });
  };

  const [timeLeft, setTimeLeft] = useState(30 * 60);

  useEffect(() => {
    const timer = setInterval(() => {
      setTimeLeft((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  const minutes = Math.floor(timeLeft / 60);
  const seconds = String(timeLeft % 60).padStart(2, "0");
  const handleNext = () => {
    if (currentQuestion < questions.length - 1) {
      setCurrentQuestion(currentQuestion + 1);
    }
  };

  const handlePrevious = () => {
    if (currentQuestion > 0) {
      setCurrentQuestion(currentQuestion - 1);
    }
  };

  const handleFinish = async () => {
    try {
      const token = localStorage.getItem("token");

      const response = await axios.post(
        "http://localhost:5000/api/evaluate",
        {
          questions,
          answers,
          interviewType:
            interviewType === "resume" ? "Resume" : "Role",
          role,
        },
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      navigate("/result", {
        state: response.data,
      });

    } catch (error) {
      console.error(error);

      toast.error("Failed to evaluate interview.");
    }
  };

  if (questions.length === 0) {
    return (
      <div className="interview-container">
        <h2>Preparing your interview...</h2>
        <p>
          Questions will appear here once generated by the AI.
        </p>
      </div>
    );
  }

  return (
    <div className="interview-container">
      <div className="interview-card">
        <div className="interview-header">
          <h2>Interview Session</h2>

          <div className="timer">
            ⏱ {minutes}:{seconds}
          </div>
        </div>

        <div className="progress-text">
          Question {currentQuestion + 1} of {questions.length}
        </div>

        <div className="progress-bar">
          <div
            className="progress-fill"
            style={{
              width: `${((currentQuestion + 1) / questions.length) * 100}%`,
            }}
          ></div>
        </div>

        <div className="question-card">
          <h3>Question {currentQuestion + 1}</h3>

          <p>{questions[currentQuestion].question}</p>
        </div>

        <textarea
          placeholder="Type your answer here..."
          value={answers[currentQuestion] || ""}
          onChange={handleAnswerChange}
        />

        <div className="character-count">
          {(answers[currentQuestion] || "").length} Characters
        </div>

        <div className="button-group">
          <button
            onClick={handlePrevious}
            disabled={currentQuestion === 0}
          >
            Previous
          </button>

          {currentQuestion === questions.length - 1 ? (
            <button
              className="finish-btn"
              onClick={handleFinish}
            >
              Finish Interview
            </button>
          ) : (
            <button
              className="next-btn"
              onClick={handleNext}
            >
              Next
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

export default Interview;