import { useState } from "react";
import "./Interview.css";

function Interview() {
  // Later this will come from the backend (Gemini)
  const [questions] = useState([]);

  const [currentQuestion, setCurrentQuestion] = useState(0);

  const [answers, setAnswers] = useState({});

  const handleAnswerChange = (e) => {
    setAnswers({
      ...answers,
      [currentQuestion]: e.target.value,
    });
  };

  const handleNext = () => {
    if (currentQuestion < questions.length - 1) {
      setCurrentQuestion(currentQuestion + 1);
    }
  };

  const handlePrevious = () => {
    if (currentQuestion > 0) {
      setCurrentQuestion(currentQuestion - 1);
    }
  };

  const handleFinish = () => {
    console.log(answers);
  };

  if (questions.length === 0) {
    return (
      <div className="interview-container">
        <h2>Preparing your interview...</h2>
        <p>
          Questions will appear here once generated by the AI.
        </p>
      </div>
    );
  }

  return (
    <div className="interview-container">
      <div className="interview-card">
        <h3>
          Question {currentQuestion + 1} / {questions.length}
        </h3>

        <h2>{questions[currentQuestion].question}</h2>

        <textarea
          placeholder="Type your answer here..."
          value={answers[currentQuestion] || ""}
          onChange={handleAnswerChange}
        />

        <div className="button-group">
          <button
            onClick={handlePrevious}
            disabled={currentQuestion === 0}
          >
            Previous
          </button>

          {currentQuestion === questions.length - 1 ? (
            <button onClick={handleFinish}>
              Finish Interview
            </button>
          ) : (
            <button onClick={handleNext}>
              Next
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

export default Interview;